### PR TITLE
fix: checkbox accessibility

### LINKED ISSUE #690: Checkbox accessibility update
**Issue:** 
1. Cannot check or uncheck the checkbox component using a keyboard
 
2. No focus control indicator

**Solution:**
1. Allow the component to be utilized via keyboard controls

2. Add focus control indicator to component

https://sds.czi.design/009eaf17b/p/548a3d-control-inputs/t/70a4ba

### PR DESCRIPTION
**Pull request by ehoops-cz**
…ocus border for keyboard nav

fix #690

## Summary

**Structural Element (Base, Gene, DNA, Chromosome or Cell)**
Github issue: [#690](https://github.com/chanzuckerberg/sci-components/issues/690)

Issue:
~~1. Cannot check or uncheck the checkbox component using a keyboard~~
2. No focus control indicator

Solution:
~~Allow the component to be utilized via keyboard controls~~
Add focus control indicator to component
Screenshot 2023-11-29 at 10 51 36 AM

Screenshot 2023-11-29 at 10 33 25 AM
Screenshot 2023-11-29 at 10 33 18 AM

## Checklist

- [x] Default Story in Storybook
- [x] LivePreview Story in Storybook
- [x] Test Story in Storybook
- [ ] Tests written
- [x] Variables from `defaultTheme.ts` used wherever possible
- [x] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

### CODE REVIEW

File: packages/components/src/core/InputCheckbox/styles.ts [hunk 1]
```diff
@@ -64,6 +68,16 @@ export const StyledCheckbox = styled(RawCheckbox)`
         }
       }
 
+      &.MuiCheckbox-root {
+        &.Mui-focusVisible {
+          outline: 5px auto Highlight;
+          outline: 5px auto -webkit-focus-ring-color;
```
Comment (ehoops-cz) [inline packages/components/src/core/InputCheckbox/styles.ts:74]: I think these outlines would be nice to have somewhere reusable.  I ran into trouble trying to make them into a mixin.

Comment (tihuan) [reply packages/components/src/core/InputCheckbox/styles.ts:74]: Wow nice focus-visible only style 🔥 !

I haven't tested this yet, but maybe this reusable function would work?

```ts
function focusVisibleA11yStyle(props: CommonThemeProps) {
  const corners = getCorners(props);
  const spaces = getSpaces(props);

  return `
    &.MuiCheckbox-root {
      &.Mui-focusVisible {
        outline: 5px auto Highlight;
        outline: 5px auto -webkit-focus-ring-color;
      }
      border-radius: ${corners?.s}px;
      padding: ${spaces?.xxs}px;
      margin: 3px;
    }
  `;
}

export const StyledCheckbox = styled(RawCheckbox)`
  ${focusVisibleA11yStyle}  // <--------- invoke it here!

  ${(props) => {
    const colors = getColors(props);
    const iconSizes = getIconSizes(props);

    return `
      color: ${colors?.gray[400]};
      &:hover {
        color: ${colors?.gray[500]};
        background-color: transparent;
      }
      &.Mui-disabled {
        color: ${colors?.gray[300]};
      }
      &.Mui-checked {
        color: ${colors?.primary[400]};
        &:hover {
          color: ${colors?.primary[500]};
          background-color: transparent;
        }
        &.Mui-disabled {
          color: ${colors?.primary[300]}
        }
      }

      .MuiSvgIcon-root {
        height: ${iconSizes?.input.height}px;
        width: ${iconSizes?.input.width}px;
      }
    `;
  }}
`;
```

File: packages/components/src/core/InputCheckbox/index.tsx [hunk 2]
```diff
@@ -67,6 +67,7 @@ const InputCheckbox = (props: CheckboxProps): JSX.Element => {
       caption={caption}
       control={
         <StyledCheckbox
+          tabIndex={0}
```
Comment (ahuth) [inline packages/components/src/core/InputCheckbox/index.tsx:70]: I'm surprised we need this, because inputs are already focusable.

If we remove this, does anything bad happen? I suspect it'll still work without it.

File: packages/components/src/core/InputCheckbox/styles.ts (hunk 1 above)
Comment (ehoops-cz) [reply packages/components/src/core/InputCheckbox/styles.ts:74]: I created a function in mixins/a11y.ts
```
export function focusVisibleA11yStyle() {
  return `
      &.Mui-focusVisible, &:focus-visible {
        outline: 5px auto Highlight;
        outline: 5px auto -webkit-focus-ring-color;
      }
  `;
}
```
And used it in the component
```
export const StyledCheckbox = styled(RawCheckbox)`
  ${(props) => {
    const colors = getColors(props);
    const corners = getCorners(props);
    const iconSizes = getIconSizes(props);
    const spaces = getSpaces(props);
    return `
      color: ${colors?.gray[400]};
      &:hover {
        color: ${colors?.gray[500]};
        background-color: transparent;
      }
      &.Mui-disabled {
        color: ${colors?.gray[300]};
      }
      &.Mui-checked {
        color: ${colors?.primary[400]};
        &:hover {
          color: ${colors?.primary[500]};
          background-color: transparent;
        }
        &.Mui-disabled {
          color: ${colors?.primary[300]}
        }
      }

      &.MuiCheckbox-root {
        ${focusVisibleA11yStyle()}
        border-radius: ${corners?.s}px;        
        padding: ${spaces?.xxs}px;
        margin: 3px;
      }

      .MuiSvgIcon-root {
        height: ${iconSizes?.input.height}px;
        width: ${iconSizes?.input.width}px;
      }
    `;
  }}
`;
```
I'm still having a small issue where the function needs to be invoked in order to work.  Same in the button:
```

    return `
      ${outlineBorder}
      ${focusVisibleA11yStyle()}
      padding: ${padding};
      min-width: 120px;
      height: 34px;
      &:hover {
        color: white;
        background-color: ${colors?.primary[500]};
        box-shadow: none;
      }
      &:active {
        color: white;
        background-color: ${colors?.primary[600]};
        box-shadow: none;
      }
      &:disabled {
        color: ${colors?.gray[400]};
        background-color: ${colors?.gray[300]};
        border-color: ${colors?.gray[300]};
      }
      .MuiButton-startIcon {
        margin-right: ${spacings?.m}px;
      }
      .MuiButton-endIcon {
        margin-left: ${spacings?.m}px;
      }
    `;
  }}
`;
```

File: packages/components/src/core/InputCheckbox/index.tsx (hunk 2 above)
Comment (ehoops-cz) [reply packages/components/src/core/InputCheckbox/index.tsx:70]: Thanks, it still works

File: packages/components/src/core/InputCheckbox/styles.ts (hunk 1 above)
Comment (ehoops-cz) [reply packages/components/src/core/InputCheckbox/styles.ts]: I created a function and using it as `${focusVisibleA11yStyle}` in the button component works, but in the checkbox i have to invoke it with `${focusVisibleA11yStyle()}`.  I'm not seeing why these would be different.

Function
```
export function focusVisibleA11yStyle() {
  return `
      &.Mui-focusVisible, &:focus-visible {
        outline: 5px auto Highlight;
        outline: 5px auto -webkit-focus-ring-color;
      }
  `;
}
```

Checkbox
```
export const StyledCheckbox = styled(RawCheckbox)`
  ${(props) => {
    const colors = getColors(props);
    const corners = getCorners(props);
    const iconSizes = getIconSizes(props);
    const spaces = getSpaces(props);
    return `
      color: ${colors?.gray[400]};
      &:hover {
        color: ${colors?.gray[500]};
        background-color: transparent;
      }
      &.Mui-disabled {
        color: ${colors?.gray[300]};
      }
      &.Mui-checked {
        color: ${colors?.primary[400]};
        &:hover {
          color: ${colors?.primary[500]};
          background-color: transparent;
        }
        &.Mui-disabled {
          color: ${colors?.primary[300]}
        }
      }

      &.MuiCheckbox-root {
        ${focusVisibleA11yStyle()}
        border-radius: ${corners?.s}px;        
        padding: ${spaces?.xxs}px;
        margin: 3px;
      }

      .MuiSvgIcon-root {
        height: ${iconSizes?.input.height}px;
        width: ${iconSizes?.input.width}px;
      }
    `;
  }}
`;
```
Button
```
const ButtonBase = styled(Button, {
  shouldForwardProp: (prop) => !sdsPropNames.includes(prop as string),
})`
  box-shadow: none;
  ${(props) => {
    const { variant } = props;
    const colors = getColors(props);
    const spacings = getSpaces(props);

    const containedPadding = `${spacings?.xs}px ${spacings?.l}px`;

    // (thuang): outline variant has border 1px, so padding needs to be smaller
    const outlinedPadding = `${(spacings?.xs || 0) - 1}px ${
      (spacings?.l || 0) - 1
    }px`;

    const padding = variant === "outlined" ? outlinedPadding : containedPadding;
    const outlineBorder =
      variant === "outlined" ? `border-color: ${colors?.primary[400]};` : "";

    return `
      ${outlineBorder}
      ${focusVisibleA11yStyle}
      padding: ${padding};
      min-width: 120px;
      height: 34px;
      &:hover {
        color: white;
        background-color: ${colors?.primary[500]};
        box-shadow: none;
      }
      &:active {
        color: white;
        background-color: ${colors?.primary[600]};
        box-shadow: none;
      }
      &:disabled {
        color: ${colors?.gray[400]};
        background-color: ${colors?.gray[300]};
        border-color: ${colors?.gray[300]};
      }
      .MuiButton-startIcon {
        margin-right: ${spacings?.m}px;
      }
      .MuiButton-endIcon {
        margin-left: ${spacings?.m}px;
      }
    `;
  }}
`;
```

Comment (tihuan) [reply packages/components/src/core/InputCheckbox/styles.ts]: Ah yes, so it depends on where `focusVisibleA11yStyle` is placed!

If we put `focusVisibleA11yStyle` inside `${(props) => { ... }}`, we'll need to manually invoke `focusVisibleA11yStyle`, like so: `${focusVisibleA11yStyle()}`, since Emotion already called the parent level function. However, if we place `focusVisibleA11yStyle` at the root styled component level, then Emotion will invoke the function for us!

E.g.,

```ts
// Root level
const Foo = styled.div`
  {focusVisibleA11yStyle}

  ...other styles
`

// Nesting focusVisibleA11yStyle inside `${(props) => {...}}

const Foo = styled.div`
  ${(props) => {
    return `
      ${focusVisibleA11yStyle(props)};

      ... other styles
    `
  }
`
```

Hope this helps!

Comment (tihuan) [reply packages/components/src/core/InputCheckbox/styles.ts]: For Button, I think we can lift the `focusVisibleA11yStyle` outside of `${(props) => { ... }}`, since it doesn't depend on anything inside that function anyway 😄 ?

Like so:

```ts
const ButtonBase = styled(Button, {
  shouldForwardProp: (prop) => !sdsPropNames.includes(prop as string),
})`
  box-shadow: none;

  ${focusVisibleA11yStyle} // <--- HERE!

  ${(props) => {
    const { variant } = props;
    const colors = getColors(props);
    const spacings = getSpaces(props);
    ...
  }
```

File: packages/components/src/core/styles/common/mixins/a11y.ts [hunk 3]
```diff
@@ -0,0 +1,8 @@
+export function focusVisibleA11yStyle() {
+  return `
+      &.Mui-focusVisible, &:focus-visible {
```
Comment (ahuth) [inline packages/components/src/core/styles/common/mixins/a11y.ts:3]: Good idea 👍 

If you wanted to, you could use this util in the Tab component I updated this morning: https://github.com/chanzuckerberg/sci-components/blob/eb6870f6d8bfe213555a5e0c0040308833510ab9/packages/components/src/core/Tabs/style.tsx#L97-L100

Or I can do it later

**Review by ahuth — APPROVED** [review]
LGTM

File: packages/components/src/core/styles/common/mixins/a11y.ts [hunk 4]
```diff
@@ -0,0 +1,8 @@
+export function focusVisibleA11yStyle() {
```
Comment (tihuan) [inline packages/components/src/core/styles/common/mixins/a11y.ts:1]: should we make this util function depend on `props`, so `5px` is not hard coded and can use `spaces`?

Comment (ehoops-cz) [reply packages/components/src/core/styles/common/mixins/a11y.ts:1]: unfortunately spaces does not have a 5px option
